"""empty message

Revision ID: 50034c04f5a8
Revises: 
Create Date: 2023-05-01 20:47:17.143154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50034c04f5a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_de_nascimento', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('procedimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_do_procedimento', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('data_e_hora_da_consulta', sa.DateTime(), nullable=False),
    sa.Column('observacoes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cobranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('data_de_vencimento', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_consulta'], ['consulta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta_procedimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('id_procedimento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_consulta'], ['consulta.id'], ),
    sa.ForeignKeyConstraint(['id_procedimento'], ['procedimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consulta_procedimento')
    op.drop_table('cobranca')
    op.drop_table('consulta')
    op.drop_table('procedimento')
    op.drop_table('cliente')
    # ### end Alembic commands ###
